name: Check crd and readme updates
on:
  pull_request:
    paths:
      - "apis/**"
jobs:
  file-updates:
    name: Test file updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run make commands
        run: |
          make generate && make manifests && make api-docs
      - name: check if crd changed
        run: |
          git status -s | grep config/
          if [[ -z $(git status -s | grep config/) ]]
          then
            echo "crd is changed"
          fi
      - name: check if doc changed
        run: |
          git status -s | grep .md
          if [[ -z $(git status -s | grep .md) ]]
            then
              echo "doc is changed"
          fi
      # - name: check unstaged files
      #   id: check_unstaged_files
      #   run: |
      #     if [[ -z $(git status -s) ]]
      #     then
      #       echo "is_files_unstaged=false" >> $GITHUB_OUTPUT
      #     else
      #       echo "is_files_unstaged=true" >> $GITHUB_OUTPUT
      #       exit
      #     fi
      # - name: create pr comments and fail checks
      #   if: ${{ steps.check_unstaged_files.is_files_unstaged }} == true
      #   run: |
      #     git log