name: Check crd and readme updates
on:
  pull_request:
    paths:
      - "apis/**"
jobs:
  file-updates:
    name: Test file updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run make commands
        run: |
          make generate && make manifests && make api-docs
      - name: check crd,apis and docs updated
        id: crd_api_update
        run: |
          crd_api_array=()
          docs_array=()
          files=$(git status --porcelain | egrep "apis|config" | cut -b4-)
          for file in $files; do
            crd_api_array+=($file)
          done
          files=$(git status --porcelain | egrep "docs/api-overview.md" | cut -b4-)
          for file in $files; do
            crd_api_array+=($file)
          done
          exit 1
      # - name: check docs updated
      #   id: docs_update
      #   run: |
      #     docs_array=()
      #     files=$(git status --porcelain | egrep "docs/" | cut -b4-)
      #     for file in $files; do
      #       crd_api_array+=($file)
      #     done
      #     echo "docs_array=$docs_array" >> $GITHUB_OUTPUT
      # - name: generate gh comments
      #   if: ${{ steps.crd_api_update.outputs.crd_api_array.length > 0 && steps.crd_api_update.outputs.docs_array.length >0 }}
      #   run: |
      #     echo $steps.crd_api_update.outputs.crd_api_array
      #     echo steps.crd_api_update.outputs.docs_array