name: Create Jira from Snyk
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  create-jira-bugs:
        uses: AjayJagan/jira-snyk-resuable-workflow/.github/workflows/jira-snyk.yaml@main
        with:
          jira_server: https://issues.redhat.com
          jira_project_id: 12340620
          jira_component_names: Platform
          jira_epic_id: RHOAIENG-1430
          snyk_org_id: ed870ef2-8f76-4ea1-ad4b-dacfa225eb69
          snyk_project_id: 570fd96f-09ad-488b-bb37-f822c34c973f
          dry_run: true
          exclude_files_path: ./.github/workflows/supporting-files/exclude_files.json
        secrets: inherit
     