name: "Pre-release"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to update(https://semver.org/).
        required: true
      tracker-url:
        type: string
        description: The URL to tracker issue(https://github.com/opendatahub-io/opendatahub-community/issues).
        required: true
env:
  VERSION: ${{ github.event.inputs.version }}
  TRACKER_URL: ${{ github.event.inputs.tracker-url }}
jobs:
  update-main-and-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
    - uses: actions/checkout@v4

    - name: Update version for main
      uses: ./.github/actions/update-release-version
      with:
        version: ${{ env.VERSION }}
        
    - name: Create PR to main
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update version to ${{ env.VERSION }}"
        branch: odh-release/version-update
        delete-branch: true
        title: "Update version to ${{ env.VERSION }}"
        # reviewers: "zdtsw"
        base: main

    - name: Checkout release branch
      run: |
        git fetch origin
        git checkout odh-${{ env.VERSION }}

    - name: Update version for release branch
      uses: ./.github/actions/update-release-version
      with:
        version: ${{ env.VERSION }}

    - name: Update manifest branches
      uses: ./.github/actions/update-manifest-branches
        
    - name: Push changes to release branch
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: odh-${{ env.VERSION }}
        message: "ODH Release ${{ env.VERSION }}: Update release branch"

    - name: Trigger process-fbc-fragment workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: process-fbc-fragment.yaml
        ref: odh-${{ env.VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
    
