name: "Pre release 1"
on:
  pull_request:
    types:
      - closed

jobs:
  push-tags-and-create-release-prs:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    # && contains(github.event.comment.body, '/release-odh')
    runs-on: ubuntu-latest
    steps:
    - name: check release comment
      uses: peter-evans/find-comment@v3
      id: release-comment
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: /release-odh
        direction: last
    - run: |
        if [[ ${{ steps.release-comment.outputs.comment-body }} -ne "/release-odh" ]]; then
        exit 0
        fi
