name: "Release: Update branches and test e2e"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to update.
        required: true
      tracker-url:
        type: string
        description: The URL to tracker issue.
        required: true
env:
  GITHUB_TOKEN: ${{ github.token }}
  VERSION: ${{ inputs.version }}
  TRACKER_URL: ${{ inputs.tracker-url }}
jobs:
  create-e2e-test-pr:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Create e2e test pr and update image tags
    steps:
      - uses: actions/checkout@v4
      - name: Update repo variables
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const script = require('./.github/scripts/update-variables.js')
            script({github, context})
      - name: Create release pr
        uses: ./.github/actions/create-release-pr
        with:
          pr-branch: "odh-release/e2e-test"
          title: "[DO NOT MERGE] Test ${{ env.VERSION }} Release"
          commit-message: "Test ${{ env.VERSION }} Release"
      - name: Wait for checks to pass
        run: ./.github/scripts/wait-for-checks.sh ${{ env.PULL_REQUEST_NUMBER }}
      - name: Close PR
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ env.PULL_REQUEST_NUMBER }}
          comment: Auto-closing pull request after success checks
          delete-branch: true
      - name: Push version tag to quay.io
        run: |
          # Need ODH creds
          # podman login -u ajaganat -p ${{ secrets.PODMAN_PASSWORD }} quay.io/ajaganat
          # podman pull quay.io/ajaganat/opendatahub-operator:pr-23
          # podman push quay.io/ajaganat/opendatahub-operator:pr-23 quay.io/ajaganat/opendatahub-operator:${{ env.VERSION }}
          echo "Successfully push tags with version: ${{ env.VERSION }}"